"""add public_id, is_admin, registeration date fields

Revision ID: 74e28d93270d
Revises: 09fa23c86966
Create Date: 2018-09-13 19:26:59.962680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e28d93270d'
down_revision = '09fa23c86966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('public_id', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('registerd_on', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'user', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'registerd_on')
    op.drop_column('user', 'public_id')
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
