"""add blacklist table

Revision ID: 896237be32ba
Revises: 0c672ef4f2eb
Create Date: 2018-09-16 14:42:24.845326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896237be32ba'
down_revision = '0c672ef4f2eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
